export enum ErrorEnum {
  EMAIL_OR_PHONE_IS_TAKEN = 'EMAIL OR PHONE IS TAKEN',
  CREDENTIALS_ARE_NOT_VALID = 'CREDENTIALS ARE NOT VALID',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  ERROR_WITH_DOWNLOAD_FILE = 'ERROR WITH DOWNLOAD FILE',
  NOT_ENOUGH_BONUSES_ON_BALANCE = 'NOT ENOUGH BONUSES ON BALANCE',
}
