export enum ErrorEnum {
  EMAIL_OR_PHONE_IS_TAKEN = 'EMAIL OR PHONE IS TAKEN',
  CREDENTIALS_ARE_NOT_VALID = 'CREDENTIALS ARE NOT VALID',
  NOT_AUTHORIZED = 'NOT_AUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  TO_USER_WITH_THIS_ID_NOT_FOUND = 'TO_USER WITH THIS ID NOT FOUND',
  NOT_ENOUGH_ACTIVE_BONUSES_ON_BALANCE = 'NOT_ENOUGH_ACTIVE_BONUSES_ON_BALANCE',
}
